### ISSUE TITLE
STOLE MY IDEA

### ISSUE THREAD

**Issue by UnrealFar** [MarzaElise/cats.py#1]
AAAAAAAAAAAAAAAAAAAAAAAAAAAH HOW DARE U STEAL MY IDEAAAAAAAAAAAAAa

**Comment by MarzaElise** [comment]
you dont "own" an idea for me to steal it. I have my rights and freedom to do whatever I like.

**Comment by MarzaElise** [comment]
and this has better implementation, better code quality and API coverage than yours. This doesnt relate to your repository in any ways.

**Comment by Genoinno** [comment]
bruh what the heck Is this issue
